//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaManager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class ManagerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ManagerSettings defaultInstance = ((ManagerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ManagerSettings())));
        
        public static ManagerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.wav,*.mp3,*.wma,*.ogg,*.midi,*.aif,*.aifc,*.aiff,*.au,*.ea")]
        public string MusicFileExt {
            get {
                return ((string)(this["MusicFileExt"]));
            }
            set {
                this["MusicFileExt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.avi,*.flv,*.wmv,*.mov,*.mp4")]
        public string VideoFileExt {
            get {
                return ((string)(this["VideoFileExt"]));
            }
            set {
                this["VideoFileExt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OtherFileExt {
            get {
                return ((string)(this["OtherFileExt"]));
            }
            set {
                this["OtherFileExt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\Public\\\\Music")]
        public string FileLocations {
            get {
                return ((string)(this["FileLocations"]));
            }
            set {
                this["FileLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TrackNumber,Title,Artist,Album")]
        public string OrderOfMusic {
            get {
                return ((string)(this["OrderOfMusic"]));
            }
            set {
                this["OrderOfMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Title,Director")]
        public string OrderOfVideo {
            get {
                return ((string)(this["OrderOfVideo"]));
            }
            set {
                this["OrderOfVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Title,Path,Size")]
        public string OrderOfOther {
            get {
                return ((string)(this["OrderOfOther"]));
            }
            set {
                this["OrderOfOther"] = value;
            }
        }
    }
}
